# Generated by Django 5.2.5 on 2025-08-15 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Debe ser un número de 8 dígitos.', regex='^\\d{8}$')], verbose_name='Documento'),
        ),
    ]
