# Generated by Django 5.2.5 on 2025-08-16 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0002_alter_user_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='latearrival',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='latearrival',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_late_arrivals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_school_staff',
            field=models.BooleanField(default=False, verbose_name='Es personal de escuela'),
        ),
    ]
