# Generated by Django 5.2.5 on 2025-08-16 02:13

import avisos.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0003_latearrival_reviewed_at_latearrival_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', avisos.models.UserManager()),
            ],
        ),
    ]
